name: Build & Publish to npmjs

on:
  push:
    tags:
      - 'v*'  # Example: v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Get version from tag and update package.json
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "Publishing version: $VERSION"
          npm version "$VERSION" --no-git-tag-version

      - name: Install dependencies & Generate static files # 安装依赖打包demo和文档
        run: |
          node -v
          npm install
          npm install gulp -g
          npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
